### ISSUE TITLE
License Condition Check Request

### ISSUE THREAD

**Issue by Zedd0202** [backslash-f/aescryptable#5]
First, I really appreciate the perfect AES256CBC source.
It seems that this project doesn't have any license policies. Could you please specify your open source policies or conditions so that it can be used for our project?
Thanks so much.

**Comment by backslash-f** [comment]
Hello and thanks. 👍 

Totally forgot about that...
Ok, I just added a [MIT license](https://github.com/backslash-f/aescryptable/commit/6d123328c3ac8c0540893fc119d37d724ad54b2b).

Cheers!

**Comment by backslash-f** [comment]
Closed by [6d1233](https://github.com/backslash-f/aescryptable/commit/6d123328c3ac8c0540893fc119d37d724ad54b2b) and [8d6134](https://github.com/backslash-f/aescryptable/commit/8d6134459d9fad3479cca9696eb2f900e89cf1f6).
